require: rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails/Output:
  Enabled: false

# Prefer character literal for certain situations such as flags
Style/CharacterLiteral:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

