require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
  NewCops: enable

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'bin/*'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/*_controller.rb'

Rails/Output:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false
