version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
  lint:
    docker:
      - image: cimg/ruby:2.7.2-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Rubocop lint
          command: bundle exec rubocop
  test:
    parallelism: 1
    docker:
      - image: cimg/ruby:2.7.2
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: steepd
          POSTGRES_DB: steepd_test
          POSTGRES_PASSWORD: steepd_test_password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: steepd
      PGPASSWORD: steepd_test_password
      RAILS_ENV: test
      IS_CI: true
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: rm db/schema.rb && bundle exec rails db:create && bundle exec rails db:migrate
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
